version: "3"

# https://tecadmin.net/docker-compose-for-mysql-with-phpmyadmin/
# https://dev.to/devkiran/app-network-docker-compose-54h7

services:

  # MySql
  mysqldb:
    image: mysql:8
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: payments
      MYSQL_PASSWORD: root
    networks:
      - app-network

  # phpmyadmin http://localhost:8090/ | usr root / pwd root
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: mysqldb
      MYSQL_ROOT_PASSWORD: root
    networks:
      - app-network
    depends_on:
      - mysqldb

networks:
  app-network:

volumes:
  db_data: